# Generated by Django 6.0.2 on 2026-03-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
