# Generated by Django 6.0.2 on 2026-03-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankaccount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('home', 'Home Loan'), ('car', 'Car Loan'), ('personal', 'Personal Loan'), ('education', 'Education Loan'), ('business', 'Business Loan')], max_length=20)),
                ('amount', models.IntegerField()),
                ('duration_months', models.IntegerField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.user')),
            ],
        ),
    ]
