# Generated by Django 6.0.2 on 2026-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('service', 'Service'), ('loan', 'Loan'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('rating', models.CharField(choices=[('5', '⭐⭐⭐⭐⭐ Excellent'), ('4', '⭐⭐⭐⭐ Good'), ('3', '⭐⭐⭐ Average'), ('2', '⭐⭐ Poor'), ('1', '⭐ Very Poor')], max_length=2)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
